spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=taskList
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: always
      continue-on-error: false
     # data-locations: classpath:demo_data.sql
  output:
    ansi:
      enabled: ALWAYS